"""empty message

Revision ID: 1478b74cca01
Revises: 254b7868ca9a
Create Date: 2021-11-27 13:33:50.038036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1478b74cca01'
down_revision = '254b7868ca9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
