"""empty message

Revision ID: 254b7868ca9a
Revises: 7ec8ae931e0c
Create Date: 2021-11-19 02:20:03.500356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254b7868ca9a'
down_revision = '7ec8ae931e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('tasks_order', sa.ARRAY(sa.Integer()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'tasks_order')
    # ### end Alembic commands ###
